### ISSUE TITLE
Threads

### ISSUE THREAD

**Issue by p1nngu** [yourfavDev/go-brute#4]
I checked the bruter and it's working brilliant , but it's scanning so slow , i guess that the issue it's all about the threads . I tried multiple threads , same speed.  Is there any way to improve the threads?

**Comment by yourfavDev** [comment]
When i wrote the code it was not an issue but now looking back at it i can see a few issues and if i have enough time i will implement a new system in a few days

**Comment by yourfavDev** [comment]
#5 Opened a pull request now but i will need someone with write access to merge it, sorry for the late response !
